### ISSUE TITLE
Dictionary Feature

### ISSUE THREAD

**Issue by yiteng-li** [taximanli/kotobade-asobou#17]
Add a link to a dictionary or add a definition of the daily word (would rlly help since im currently studying Japanese)

**Comment by taximanli** [comment]
Good suggestion! I've added dictionary feature (powered by jisho.org) in couple of places in the latest update.

1. In statistics pop-up, it now shows yesterday's word and when you click on the word, it searches the word definition.
2. Added a search button to search the word entered in the text box.
3. Can click on the revealed words to search them in jisho.org.

**Comment by briantist** [comment]
@taximanli I love that feature! But I think there's a bug in it. In today's game, the pop up showed yesterday's answer/link to jisho.

I've blocked out the word to avoid spoiling for anyone, but you can see the title refers to Game #47 (correctly) while the dictionary  line refers to game #46, and the word shown/linked to was indeed 46's word.

<img width="271" alt="image" src="https://user-images.githubusercontent.com/1260690/157910062-290a228d-b37a-4f96-a96a-45b58b1b90b7.png">

**Comment by briantist** [comment]
Ah I just re-read your comment that it shows yesterday's word 🤦‍♂️so it seems that was intentional, but why show yesterday's and not today's?

**Comment by taximanli** [comment]
Yes, it was intentional not to show today's word as an effort for avoiding spoilers for anyone else, but to show yesterday's word for players to review (perhaps they didn't guess it right yesterday). I used game number to label the word instead of labelling it yesterday's word because I'm seriously considering using Japan Standard Time as the standard time for all players across the world. Perhaps I should label it "previous word" to be clearer instead?
