### ISSUE TITLE
Hints related to small tsu "っ" show the incorrect column

### ISSUE THREAD

**Issue by mcmilnick** [taximanli/kotobade-asobou#24]
**Describe the bug**
When solving a puzzle, I got a hint showing me it was a hiragana in the same column aka the up down arrows. This happened for ’ち’, but the answer ended up being small tsu ’っ’. This is actually a column over. It seemed to be querying off of the regular つ.
![bug_pic](https://user-images.githubusercontent.com/10985456/162132892-51be46d4-f0f5-42fd-a84c-c213dd77d3c8.PNG)

**Comment by mcmilnick** [comment]
After looking through your hint tables, I think I agree. The thing that throws me, is that for the current table layout, I think the hints are confusing. I think for the current table, the hints should be as follows...

export const CONSONANT_STATUS_KANA = [
  'あいうえおぁぃぅぇぉ',
  'かきくけこがぎぐげご',
  'さしすせそざじずぜぞ',
  'たちつてとだぢづでど',
  'なにぬねのっ',
  'はひふへほばびぶべぼぱぴぷぺぽ',
  'まみむめもぱぴぷぺぽ',
  'やゆよゃゅょ',
  'らりるれろ',
  'わんをーゔ',
]

export const VOWEL_STATUS_KANA = [
  'わらやまはなたさかあ',
  'りみひにちしきい',
  'んるゆむふぬつすくう',
  'れめへねてせけえ',
  'をろよもほのとそこお',
  'ーゃぱばだざがぁ',
  'ぴびぢじぎぃ',
  'ゔゅぷぶっづずぐぅ',
  'ぺべでぜげぇ',
  'ょぽぼどぞごぉ',
]

I do, however, think that your the current hints are more logical for the language. I therefore think the table should be rearranged to make the hints following the logical flow of the display.

**Comment by mcmilnick** [comment]
I learned to fish...
https://github.com/taximanli/kotobade-asobou/pull/26
https://github.com/taximanli/kotobade-asobou/pull/25

By all means, feel free to disagree and let me know what you think. I split my changes into 2 patches though it could have been one PR. Even if you don't like the layout changes, I do think that ゔ belongs in the hints.

**Comment by taximanli** [comment]
Thanks @mcmilnick for your good points and great effort in improving the game.

I agree that the layout of rows and columns in the kana chart is not 100% perfect because I want to keep the key panel compact to accommodate smaller screen size (e.g. mobile screen). And as you have noticed, I've designed the current hints to be logical for the Japanese language.

To emphasize that ー ゔ ん are different from the other normal kana, they are now marked with borders to show that they are separated from the main kana chart.

![image](https://user-images.githubusercontent.com/11369846/170708400-c057637e-f841-443f-9e9d-607a67772e16.png)

And for the kana ゔ, I've added this in the hints.

`Both the kana ん and the long sound mark ー do not have any matching rows or columns. And the kana ゔ does not have matching columns.`
